todolist/item/urls.py
from django.urls import path
from . import views

app_name = "todolist"

urlpatterns = [
    path('', views.TodoList.as_view(), name='todo_all'),
    path('complete/', views.TodoListComplete.as_view(), name='todo_completed'),
    path('incomplete/', views.TodoListIncomplete.as_view(), name='todo_incompleted'),
    path('<int:pk>/', views.TodoDetail.as_view(), name='todo_detail'),
    path('new', views.TodoCreate.as_view(), name='todo_new'),
    path('edit/<int:pk>/', views.TodoUpdate.as_view(), name='todo_update'),
    path('delete/<int:pk>/', views.TodoDelete.as_view(), name='todo_delete'),
]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('item.urls')),
]

todolist/item/models.py
from django.db import models


class TodoItem(models.Model):
    title = models.CharField(max_length=25)
    description = models.TextField(max_length=250)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return self.title

todolist/item/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import TodoItem


class TodoList(ListView):
    model = TodoItem
    queryset = TodoItem.objects.all()


class TodoListComplete(ListView):
    model = TodoItem
    queryset = TodoItem.objects.filter(finished="True")
    template_name = 'item/todoitem_complete.html'


class TodoListIncomplete(ListView):
    model = TodoItem
    queryset = TodoItem.objects.filter(finished="False")
    template_name = 'item/todoitem_incomplete.html'


class TodoDetail(DetailView):
    model = TodoItem


class TodoCreate(CreateView):
    model = TodoItem
    fields = ['title', 'description', 'finished']
    
    def get_success_url(self):
        return reverse('todolist:todo_detail', kwargs={'pk': self.object.pk})


class TodoUpdate(UpdateView):
    model = TodoItem
    fields = ['finished']
    template_name = 'item/todoitem_confirm_finish.html'
    success_url = reverse_lazy('todolist:todo_all')


class TodoDelete(DeleteView):
    model = TodoItem
    success_url = reverse_lazy('todolist:todo_all')

todolist/item/templates/item/list_template.html
<h1>
    // TODOs
    <a href="{% url 'todolist:todo_new' %}"><i class="fas fa-plus"></i></a>
</h1>
<p>
    <a href="{% url 'todolist:todo_completed' %}">Complete</a>
    <a href="{% url 'todolist:todo_incompleted' %}">Incomplete</a>
    <a href="{% url 'todolist:todo_all' %}">All</a>
</p>

<table class="todolist_table">
    {% for todo in object_list %}
        <tr>
            <td class="padding_right">
                <h5>
                    <span
                        {% if todo.finished %}
                            class="finished_item"
                        {% endif %}
                    >
                        {{ todo.title }}
                    </span>
                </h5>
            </td>

            <td class="padding_icon"><a href="{% url 'todolist:todo_detail' todo.id %}"><i class='fas fa-bars'></i></a></td>
            <td class="padding_icon"><a href="{% url 'todolist:todo_delete' todo.id %}"><i class='fas fa-times'></i></a</td>
        </tr>
    {% empty %}
        <tr><td class="padding_right"><h5>Click the + to get started.</h5></td></tr>
    {% endfor %}
</table>

todolist/item/templates/item/todoitem_complete.html
{% extends 'base.html' %}

{% block body_block %}
    {% include "item/list_template.html" %}
{% endblock %}

todolist/item/templates/item/todoitem_confirm_delete.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>Delete "{{ object.title }}"</h1>

    <div class="row">
        <div class="col-md-8">
            <form method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ object.title }}" ?</p>
                <input type="submit" value="Confirm" />
            </form>
        </div>

        <div class="col-md-4 text-left">
            <a href="{% url 'todolist:todo_detail' object.id %}">View Task Details</a>
            <br />
            <a href="{% url 'todolist:todo_all' %}">All Tasks</a>
        </div>
    </div>
{% endblock %}

todolist/item/templates/item/todoitem_confirm_finish.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>{{ object.title }}</h1>
    <h4>{{ object.description }}</h4>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

todolist/item/templates/item/todoitem_detail.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>{{ object.title }}</h1>

    <div class="row">
        <div class="col-md-8">
            <p>{{ object.description }}</p>
            <p>
                {% if object.finished %}
                    Currently completed
                {% else %}
                    Currently not completed
                {% endif %}
            </p>
        </div>

        <div class="col-md-4 text-left">
            <a href="{% url 'todolist:todo_update' object.id %}">Change Completion Status</a>
            <br />
            <a href="{% url 'todolist:todo_delete' object.id %}">Delete</a>
            <br />
            <a href="{% url 'todolist:todo_all' %}">All tasks</a>
        </div>
    </div>
{% endblock %}

todolist/item/templates/item/todoitem_form.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>Create Something TODO</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
    <a href="{% url 'todolist:todo_all' %}">All Tasks</a>
{% endblock %}

todolist/item/templates/item/todoitem_incomplete.html
{% extends 'base.html' %}

{% block body_block %}
    {% include 'item/list_template.html' %}
{% endblock %}

todolist/item/templates/item/todoitem_list.html
{% extends 'base.html' %}

{% block body_block %}
    {% include "item/list_template.html" %}
{% endblock %}

todolist/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>Hello everybody</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>

    <body>
        <div class="continer">
            <div id="spacing">
                <div class="text-center">
                    {% block body_block %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>